export const styles = {
  container: {
    flex: 1,
    height: 640,
    width: 375,
    display: "flex",
    flexDirection: "column",
    background: "#FFFFFF",
    borderRadius: 24,
  },
  title: {
    marginTop: 32,
    marginLeft: 32,
    left: "8.53%",
    right: "54.93%",
    top: "5.18%",
    bottom: "89.64%",
    fontFamily: "Montserrat",
    fontWeight: "800",
    fontSize: 24,
    lineHeight: "132%",
    display: "flex",
    alignItems: "center",
    letterSpacing: 0.25,
    color: " #12121F",
  },
  product: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: 120,
    width: 311,
    marginLeft: 32,
    marginRight: 32,
    marginTop: 24,
    borderRadius: 24,
  },
  selectedProduct: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    height: 120,
    width: 311,
    marginLeft: 32,
    marginRight: 32,
    marginTop: 24,
    borderRadius: 24,
    backgroundColor: "#FEF2EE",
  },
  image: {
    height: 100,
    width: 100,
    marginLeft: 18,
    backgroundPosition: "center",
    backgroundRepeat: "no-repeat",
    backgroundSize: 100,
  },
  groupText: {
    height: "100%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-between",
  },
  titleProduct: {
    marginTop: 16,
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 14,
    display: "flex",
    alignItems: "center",
    letterSpacing: "0.25",
    color: "#FE805C",
    width: 160,
    height: 20,
  },
  descriptionProduct: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "400",
    fontSize: 12,
    letterSpacing: 0.25,
    color: "#AFAFBD",
    width: 160,
    height: 16,
  },
  priceProduct: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 14,
    letterSpacing: 0.25,
    color: "#12121F",
    width: 160,
    height: 16,
    marginBottom: 24,
  },
  bottomCard: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
  },
  card: {
    marginTop: 10,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginLeft: 32,
    marginRight: 32,
    height: 48,
    width: 311,
    backgroundColor: "#F9F9FC",
    borderRadius: 24,
  },
  titleBottoCard: {
    fontFamily: "Montserrat",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 16,
    letterSpacing: 0.25,
    color: "#12121F",
    marginLeft: 24,
  },
  dropIconBottomCard: {
    marginRight: 21.07,
  },
};
